version: '3.8'
services:
  db:
    image: postgres:15 # Use a specific PostgreSQL version
    container_name: bobatcal-db
    restart: always
    environment:
      POSTGRES_USER: bobatcal_user
      POSTGRES_PASSWORD: bobatcal_password # Replace with a strong password in production!
      POSTGRES_DB: bobatcal_db
    ports:
      - "5433:5432" # Map host port 5433 to container port 5432 to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
